# Generated by Django 4.0.3 on 2022-03-21 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('G44', 'G44'), ('ZMM', 'ZMM'), ('G45S', 'G45S'), ('G45N1', 'G45N2'), ('KWT', 'KWT')], max_length=30)),
                ('zone', models.CharField(max_length=30)),
                ('buildingName', models.CharField(max_length=30)),
                ('buildingCode', models.CharField(max_length=30)),
                ('mtrNo', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=30)),
                ('revenue', models.CharField(max_length=30)),
            ],
        ),
    ]
