# Generated by Django 3.1.14 on 2022-03-23 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Buildings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=20)),
                ('zone', models.CharField(max_length=30)),
                ('buildingName', models.CharField(max_length=30)),
                ('buildingCode', models.CharField(max_length=30)),
                ('mtrNo', models.CharField(max_length=30)),
                ('token', models.CharField(max_length=30)),
                ('revenue', models.CharField(max_length=30)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
